import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/header-top";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sayohatchi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={`${inter.variable} antialiased`}
      >
        <HeaderTop/>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
